name: Check-on-merge
on:
  push:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update python
        run: sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt install python3.12
      - name: Install poetry
        run: pip install poetry==1.7.1
      - name: Install deps
        run: poetry install
      - name: run mypy
        run: poetry run mypy .
